import { TCareer } from '@/app/(pages)/(main)/_constant/types'

export const CAREER_BLQ: TCareer = {
  id: 5,
  companyName: '주식회사 비엘큐',
  webUrl: 'https://www.testvalley.co.kr',
  department: '프로덕트팀',
  jobPosition: '프론트엔드 개발자(사원)',
  period: ['2023. 05', '2024. 02'],
  stack: [
    'React.js',
    'Next.js',
    'Redux',
    'Redux-saga',
    'Typescript',
    'Emotion CSS',
    'Zustand',
    'Tailwind CSS',
    'Turborepo',
    'Github Action',
    'AWS CodeDeploy',
  ],
  description:
    '전자제품 판매, 체험, 중고판매등 사용자 경험이 구매로 이어질 수 있도록 서비스를 제공하는 이커머스 솔루션 <strong>테스트밸리의 개발,운영</strong>, 전자제품 빠른 매입과 사용자간의 중고거래가 가능한 서비스인 <strong>퀵셀의 백오피스 개발,운영</strong> 하였습니다.<br/>' +
    '개발 아티클 공유, Jira Task 문서화 템플릿, 온보딩 가이드 문서화 등의 활동을 통해, 동료와 함께 성장하고자 했으며 비효율적인 업무 프로세스를 개선하기 위해 노력했습니다.',
  summary: [
    'B2C 가전제품 판매, 체험, 중고판매 서비스, <strong>테스트밸리</strong>의 개발/운영',
    'B2B/B2C 중고거래 서비스, <strong>퀵셀</strong>의 개발/운영',
    '메세지서버 백오피스 개발/운영',
    '비엘큐 백오피스 서비스 모노레포 적용 및 마이그레이션 진행',
  ],
  project: [
    {
      id: 50,
      name: '백오피스 모노레포 설계, 세팅, 마이그레이션 프로젝트',
      summary:
        '기존 백오피스 서비스의 레거시를 해결하고, 개발 효율 증가를 위한 백오피스 모노레포 전환 프로젝트',
      link: '',
      period: ['2023. 07', '2023. 08'],
      skills: [
        'Next.js 13',
        'Typescript',
        'Turborepo',
        'Tailwindcss',
        'Zustand',
        'React-hook-form',
        'Github Action',
        'AWS CodeDeploy',
      ],
      details: ['<strong>참여 인원 : </strong> 1명 (FE 1명)'],
      roles: [
        '모노레포 사전 세팅하여, 이후 진행할 프로젝트의 <strong>백오피스 환경 구축 시간 단축</strong>에 기여',
        '공통 컴포넌트, 커스텀 훅, 유틸, 환경변수등 구조를 잡고 <strong>문서화하여 팀원들에게 공유</strong>',
        '개발시 기능 구현에 집중 할 수 있도록 <strong>모노레포 공통 UI 컴포넌트 개발 & 내제화 진행</strong> (기여도 90%)',
        'Git flow를 사용하면서 <strong>모노레포의 버전관리를 위한 배포 프로세스를 정리</strong>하여 팀원들에게 공유 (기여도 100%)',
        '서비스 별 배포를 위한 <strong>Github Action Workflow 스크립트 작성</strong>(기여도 60%)',
      ],
    },
    {
      id: 51,
      name: '퀵셀 백오피스 서비스 개발',
      summary: '신규 서비스 퀵셀의 백오피스 개발 프로젝트',
      link: '',
      period: ['2023. 07', '2024. 02'],
      skills: ['Next.js 13', 'Typescript', 'React-hook-form', 'Tailwind-CSS', 'Zustand'],
      details: ['<strong>참여 인원 : </strong> 5명 (FE 2명, BE 3명)'],
      roles: [
        '<strong>프론트엔드 리드 개발</strong>',
        '프로젝트 세팅 및 환경, CI/CD 세팅(기여도 100%)',
        '서비스별 CSS Color 변수화, 레이아웃 공통화를 위한 디자인 가이드 제작, 개발 진행',
        '<strong>메뉴관리, 카테고리, 브랜드</strong> 기능에 필요한 Drag and Drop 메뉴 컴포넌트 데이터 셋 설계 개발에 참여',
        '사전 개발 세팅과 준비를 통한 개발 시간 단축으로 테스트기간 확보',
      ],
    },
    {
      id: 52,
      name: '테스트밸리 백오피스 서비스 마이그레이션',
      summary: '운영중인 테스트밸리 백오피스 백오피스 마이그레이션 프로젝트',
      link: '',
      period: ['2023. 12', '2024. 01'],
      skills: ['Next.js 13', 'Typescript', 'React-hook-form', 'Tailwind-CSS', 'Zustand'],
      details: ['<strong>참여 인원 : </strong> 2명 (FE 1명, BE 1명)'],
      roles: [
        '테스트밸리 백오피스의 <strong>운영 리소스 감소를 위해 모노레포로 마이그레이션</strong> 작업 진행 (기여도 80%)',
        '신규 메뉴 개발 및 제품 등록 페이지 고도화 (기여도 90%)',
        '최소한의 리소스로 짧은 기간 내에 <strong>메뉴 17개(80%) 마이그레이션 완료</strong>',
        '슬랙 봇 명령어로 추가/삭제/관리를 진행하는 데이터 관리 메뉴 추가로 <strong>운영 이슈 감소</strong>에 기여(사용자 실수로 인한 수정요청 횟수 80% 감소)',
      ],
    },
    {
      id: 53,
      name: '메세지서버 백오피스 서비스 개발',
      summary: '운영되는 서비스들의 FCM 앱 푸시, 알림톡 발송 관리를 위한 메세지서버 백오피스 개발',
      link: '',
      period: ['2023. 10', '2023. 11'],
      skills: ['Next.js 13', 'Typescript', 'React-hook-form', 'Tailwind-CSS', 'Zustand'],
      details: ['<strong>참여 인원 : </strong> 2명 (FE 1명, BE 1명)'],
      roles: [
        '기존 백엔드 DB에서 관리되던 앱 푸시, 알림톡 템플릿 관리 개발 (기여도 80%)',
        '앱 FCM 예약 발송 기능 개발',
        'iFrame으로 서비스별 백오피스에 내제화 할수 있게 개발하여 기간 50% 단축',
        '마케팅-개발 부서간의 리소스 부족으로 인한 <strong>마케팅 병목현상 해소로 서비스 리텐션 지표 32% 상승</strong>, 개발팀 리소스 확보(평균 주 1MD 리소스 확보)',
        '템플릿, 파라미터를 검수하는 단계를 추가하여, <strong>오타 이슈 발생률 감소</strong>',
        'static export하여 <strong>서버 자원 감소에 기여 (메모리 리소스 감소)</strong>',
      ],
    },
    {
      id: 54,
      name: 'B2C 테스트밸리 프로모션 이벤트 페이지 제네레이터 개발',
      summary:
        '정적 페이지로 개발되는 테스트밸리의 이벤트 페이지를 마케터가 구성할 수 있도록 백오피스에 내제화 하는 프로젝트',
      link: '',
      period: ['2023. 06', '2023. 06'],
      skills: ['React', 'Next.js 12', 'Typescript', 'Emotion', 'Context-api'],
      details: ['<strong>참여 인원 : </strong> 3명 (FE 1명, BE 1명, Design 1명)'],
      roles: [
        '마케팅 팀의 요구사항과 <strong>필요한 기능을 설문을 통해 조사</strong> 후, 취합하여 구조 설계',
        '백엔드 개발자의 리소스가 부족하여 <strong>웰로의 설문조사 기능을 벤치마킹</strong>하여 Json 형식의 데이터를 DB에 저장하도록 설계하고, <strong>기능단위의 컴포넌트로 분리하여 확장성에 용이하도록 설계</strong>',
        '이벤트 페이지 제작 요청 리소스 감소에 기여 <strong>(주 1~2MD의 프론트엔드 개발자 리소스 확보)</strong>',
      ],
    },
    {
      id: 55,
      name: '기타 프로젝트',
      summary: '',
      link: '',
      period: ['2023. 05', '2024. 02'],
      skills: [],
      details: [],
      roles: [
        '테스트밸리 사용자/백오피스 멤버십 기능 개발 (기여도 100%) - 23.07.13 ~ 23.07.25',
        '퀵셀 중고거래 유도 페이지 개발',
        '퀵셀 소개페이지 개발',
        '테스트밸리 백오피스 이미지 썸네일 등록 기능 최적화',
      ],
    },
  ],
}
