import { TCareer } from '@/app/(pages)/resume/_constant/types'

export const CAREER_LAUD: TCareer = {
  id: 6,
  companyName: '주식회사 라우드',
  webUrl: 'https://www.dearmyhome.co.kr/',
  department: '프로덕트팀',
  jobPosition: '프론트엔드 개발 팀장',
  period: ['2024. 04', '2025. 04'],
  stack: [
    'React.js',
    'Next.js 14 App router',
    'Typescript',
    'Zustand',
    'React-Query',
    'Tailwind CSS',
    'Turborepo',
    'Flutter',
    'webview_flutter 4',
    'firebase_message',
    'Github Action',
    'AWS CodeDeploy',
  ],
  description:
    '인테리어 견적부터 직시공을 통해 사용자가 간편하게 인테리어 시공 서비스를 제공 받을 수 있는 <strong>디어마이홈의 개발,운영</strong>' +
    '인테리어 시공업자들에게 자사의 마루 제품을 판매하기 위한 <strong>자사몰 서비스의 마이그레이션</strong>을 진행하였습니다.<br/><br/>' +
    '<strong>서비스 개발의 0 to 1을 경험</strong>하고, 프론트엔드 팀장 역할을 같이하며 <strong>팀원 관리 능력을 성장</strong>시키기위해 노력했습니다.',
  summary: [
    '인테리어 견적 문의부터 직시공까지 간편하게 연결하는 인테리어 시공 서비스 <strong>디어마이홈</strong>의 개발/운영',
    'B2B 시공 자재판매 <strong>자재몰 서비스</strong>의 디어마이홈 서비스에 마이그레이션',
    '디어마이홈 Flutter 하이브리드앱 개발/운영',
    '백오피스 개발/운영',
  ],
  project: [
    {
      id: 63,
      name: '디어마이홈 Flutter 하이브리드 앱 개발',
      summary: '사용자 인입을 증가시키고, 편의성을 개선하기 위한 하이브리드 앱 개발 프로젝트',
      link: '',
      period: ['2024. 12', '2025. 01'],
      skills: ['Flutter', 'Firebase_message', 'webview_flutter 4', 'portone_flutter(v1)'],
      details: ['<strong>참여 인원 : </strong> 2명 (FE 1명, BE 1명)'],
      roles: [
        '웹-앱 브릿지 함수 기능 개발',
        '포트원 v1 결제, 본인 인증 웹뷰 페이지 연동',
        '파이어베이스 메세지, 토픽 연동',
        '카카오, 애플 로그인 연동',
        '네이티브 기능(카메라, 앨범, GPS) 연동',
      ],
    },
    {
      id: 62,
      name: '디어마이홈 서비스 운영/고도화',
      summary:
        '디어마이홈 서비스의 기능과 백오피스에서 사용자의 관리 피로도를 낮추기위해 기능을 고도화하는 프로젝트',
      link: '',
      period: ['2024. 06', '2025. 04'],
      skills: ['Next.js 14', 'Typescript', 'Tailwindcss', 'Zustand', 'React-hook-form'],
      details: ['<strong>참여 인원 : </strong> 4명 (FE 1명, BE 1명, Design 1명, PM 1명)'],
      roles: [
        '[백오피스] 1차 기능 고도화 - 자재몰 마이그레이션 DB구조 변경 사전작업 및 백오피스 고도화 (2024.06 ~ 2024.07)',
        '[사용자] 1차 기능 고도화 - 사용자 화면 성능 최적화 및 SEO 적용 (2024.06 ~ 2024.07)',
        '[사용자/백오피스] 사이트맵 동적 생성 기능 개발 (2024.07.04 ~ 2024.08.02)',
        '[사용자/백오피스] 이벤트 등록 기능 개발 (2024.07.22 ~ 2024.07.24)',
        '[사용자] 디자인 리뉴얼 및 메인 개편 (with 자재몰) (2024.08.05 ~ 2024.09.23)',
        '[사용자/백오피스] 자재몰 기능 마이그레이션 (2024.08.05 ~ 2024.08.20)',
        '[사용자] 카카오맵을 사용한 인테리어 지도 기능 개발 (2024.10.28 ~ 2024.11.15)',
        '[사용자] chartjs 라이브러리를 사용한 인테리어 견적 시세 그래프 기능 개발 (2024.10.28 ~ 2024.11.15)',
        '[사용자/백오피스] 메인 개편 (2025.02.10 ~ 2025.02.20)',
      ],
    },
    {
      id: 61,
      name: '디어마이홈 서비스 개발',
      summary: '투자 IR과 빠른 서비스 런칭을 위한 디어마이홈 서비스 1차 개발 프로젝트',
      link: '',
      period: ['2024. 04', '2024. 06'],
      skills: [
        'Next.js 14',
        'Typescript',
        'Turborepo',
        'Tailwindcss',
        'Zustand',
        'React-hook-form',
        'Github Action',
        'AWS CodeDeploy',
      ],
      details: ['<strong>참여 인원 : </strong> 5명 (FE 2명, BE 1명, Design 1명, PM 1명)'],
      roles: [
        '프론트엔드 팀원 <strong>일정 관리</strong> 및 백오피스 개발 지원',
        '대화형 견적 신청 기능 개발',
        '시공사례 기능 개발',
        '카카오, 애플 로그인 기능 연동',
        '포트원 v2 결제, 본인 인증 연동',
        '모노레포 Foundation component 개발',
        '모노레포 프로젝트 세팅 및 배포 스크립트 작성 (기여도 90%)',
      ],
    },
    {
      id: 60,
      name: '디어마이홈 백오피스 개발',
      summary: '디어마이홈 사내 직원용 백오피스 서비스 개발',
      link: '',
      period: ['2024. 05', '2024. 06'],
      skills: [
        'Next.js 14',
        'Typescript',
        'Turborepo',
        'Tailwindcss',
        'Zustand',
        'React-hook-form',
        'Github Action',
        'AWS CodeDeploy',
      ],
      details: ['<strong>참여 인원 : </strong> 4명 (FE 2명, BE 1명,세 PM 1명)'],
      roles: [
        '1차 개발 중간 <strong>팀원의 퇴사</strong>로 인한 백오피스 개발 F/W',
        '견적/주문 관리 메뉴 개발 (기여도 100%)',
        '컨텐츠 관리 메뉴 개발 (기여도 100%)',
        '라벨링(카테고리) 관리 메뉴 개발 (기여도 100%)',
        '알림톡/앱푸시 관리 메뉴 개발 (기여도 100%)',
        '시공기사 모바일 접근용 페이지 개발 (기여도 50%)',
        '회원 관리 메뉴 개발 (기여도 50%)',
        'Tinymce Editor 라이브러리를 사용한 에디터 컴포넌트 개발(기여도 100%)',
      ],
    },
  ],
}
