export const mdxStyles = {
  h1: 'tracking-tigh mt-10 mb-4 text-4xl font-bold text-red-500',
  h2: 'mt-8 mb-3 text-3xl font-bold tracking-tight',
  h3: 'mt-6 mb-2 text-2xl font-semibold tracking-tight',
  h4: 'mt-4 mb-2 text-xl font-semibold tracking-tight',
  h5: 'mt-2 mb-1 text-lg font-semibold tracking-tight',
  p: 'my-4 leading-7',
  a: 'text-blue-600 hover:underline dark:text-blue-400',
  ul: 'my-4 list-disc pl-6',
  ol: 'my-4 list-decimal pl-6',
  li: 'my-2',
  blockquote: 'my-4 border-l-4 pl-4 italic',
  pre: 'block rounded-md bg-gray-100 p-4 font-mono text-sm dark:bg-gray-800 overflow-x-auto',
  code: 'rounded-md bg-gray-100 px-2 py-1 font-mono text-sm dark:bg-gray-800',
} as const
