import type { EditorThemeClasses } from 'lexical'
import { mdxStyles } from './styles'

export const editorTheme: EditorThemeClasses = {
  ltr: 'text-left',
  rtl: 'text-right',
  paragraph: mdxStyles.p,
  quote: mdxStyles.blockquote,
  heading: {
    h1: mdxStyles.h1,
    h2: mdxStyles.h2,
    h3: mdxStyles.h3,
    h4: mdxStyles.h4,
    h5: mdxStyles.h5,
  },
  list: {
    nested: {
      listitem: mdxStyles.li,
    },
    ol: mdxStyles.ol,
    ul: mdxStyles.ul,
    listitem: mdxStyles.li,
  },
  image: 'editor-image',
  link: mdxStyles.a,
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: mdxStyles.code,
  },
  code: mdxStyles.pre, // Lexical's top-level 'code' is for code blocks, which corresponds to our 'pre'
  codeHighlight: {
    atrule: 'text-purple-600',
    attr: 'text-purple-600',
    boolean: 'text-pink-600',
    builtin: 'text-pink-600',
    cdata: 'text-gray-500',
    char: 'text-green-600',
    class: 'text-orange-600',
    'class-name': 'text-orange-600',
    comment: 'text-gray-500',
    constant: 'text-pink-600',
    deleted: 'text-red-600',
    doctype: 'text-gray-500',
    entity: 'text-red-600',
    function: 'text-purple-600',
    important: 'text-purple-600',
    inserted: 'text-green-600',
    keyword: 'text-blue-600',
    'maybe-class-name': 'text-orange-600',
    namespace: 'text-yellow-600',
    number: 'text-pink-600',
    operator: 'text-yellow-600',
    prolog: 'text-gray-500',
    property: 'text-red-600',
    punctuation: 'text-gray-700',
    regex: 'text-yellow-600',
    selector: 'text-green-600',
    string: 'text-green-600',
    symbol: 'text-pink-600',
    tag: 'text-blue-600',
    url: 'text-red-600',
    variable: 'text-orange-600',
  },
}
