import { IExperience } from '@/app/(pages)/resume/_components/experience/types'

const experience: IExperience = {
  isShow: true,
  experienceList: [
    {
      companyName: '라우드',
      logoName: 'laud',
      serviceSummary: [
        '인테리어 “견적-상담-직시공” 과정을 간소화하여 사용자와 인테리어 업자를 연결하는 **인테리어 B2C 서비스 “디어마이홈” 개발 운영**',
      ],
      experienceSummary: [
        '프로덕트 개발의 **0 to 1 전 과정을 직접 경험**하면서, 그동안 쌓아온 **기술 역량을 점검**하고 한 단계 성장했다는 자신감을 얻었습니다.',
        '또한, 이전에는 경험이 없던 앱 개발이나 인프라 관리 업무에 대해서도, 주도적으로 학습하고 해결 방안을 모색하여 의미 있는 성과를 만들어냈습니다.',
      ],
      employmentStatus: 'recommended_retire',
      historyList: [
        {
          department: '프로덕트팀',
          role: '프론트엔드 개발자',
          period: ['2024-04-15', '2025-04-15'],
          workingList: [
            '프론트엔드 프로젝트, 모노레포 설계/세팅',
            'B2C 인테리어 직시공 플랫폼 “디어마이홈” 개발',
            '챗봇 대화형 견적 상담 기능 설계/개발',
            '카카오맵을 이용한 시공사례 인테리어 지도 기능 개발',
            '디어마이홈 Flutter 하이브리드 앱 개발/런칭',
            '어드민 개발 - 디어마이홈, FCM 메세지서버',
            '프론트엔드 AWS 배포 파이프라인, CI/CD 관리',
          ],
          skillNameList: [
            'react.js',
            'next.js 14 app router',
            'typescript',
            'zustand',
            'react-query',
            'react-hook-form',
            'tailwind-css',
            'turborepo',
            'flutter',
            'github-actions',
            'aws',
            'gtm',
            'ga',
            'jira',
            'confluence',
          ],
        },
      ],
    },
    {
      companyName: '비엘큐',
      logoName: 'blq',
      serviceSummary: [
        '전자제품 판매, 체험, 중고판매 등 사용자 경험이 구매로 이어질 수 있는 **B2C 전자제품 커머스 “테스트밸리” 개발 운영**',
        '사진 감가 분석 AI로 감가 금액을 측정하여 중고 전자제품을 매입하고, 사용자간의 중고 거래를 중계하는 **B2B2C 중고거래 서비스 “퀵셀” 개발 운영**',
      ],
      experienceSummary: [
        '기술 스택 전환을 목표로 팀에 합류했으며, 마케팅팀과의 협업 과정에서 자주 발생하던 업무 병목 지점을 찾아 해결하고 **효율적인 프로세스를 구축**하는 데 집중했습니다.',
        '또한, 개발 히스토리나 관련 문서가 부족한 상황에서, 동료들의 원활한 업무 진행과 팀 전체의 유지보수 효율성 증대를 위해 **개발 관련 문서화를 주도적으로 진행**했습니다.',
      ],
      employmentStatus: 'recommended_retire',
      historyList: [
        {
          department: '프로덕트팀',
          role: '프론트엔드 개발자',
          period: ['2023-05-22', '2024-02-29'],
          workingList: [
            'B2C 전자제품 체험,구매 서비스 “테스트벨리” 개발 운영',
            'B2C 중고거래, 중고 제품 자사 매입/판매 서비스 “퀵셀” 어드민 개발',
            'FCM 메세지서버 어드민 개발',
            '테스트밸리 프로모션 이벤트 페이지 빌더 설계/개발',
            '어드민 모노레포 마이그레이션 설계/개발',
            '상세페이지 페이지 성능 분석 및 최적화',
            '검색/기획전/상세페이지 SEO 개선을 위한 Sitemap 등록 기능 개발',
          ],
          skillNameList: [
            'react.js',
            'next.js 13 app router',
            'typescript',
            'zustand',
            'redux',
            'react-query',
            'react-hook-form',
            'tailwind-css',
            'emotion',
            'daisyUI',
            'ant-design',
            'turborepo',
            'github-actions',
            'aws ec2',
            'gtm',
            'ga',
            'hackle',
            'jira',
            'confluence',
          ],
        },
      ],
    },
    {
      companyName: '웰로',
      logoName: 'wello',
      serviceSummary: [
        '국민의 정책 소외 문제 해결을 위한 B2C 정책 큐레이션 서비스 “웰로” 개발',
        '기업의 정부 지원정책 추천/매칭/관리 구독 서비스 B2B SaaS “웰로비즈” 개발',
      ],
      experienceSummary: [
        'B2C 및 B2B 서비스 개발 과정에서 사용자 중심의 UI/UX를 깊이 있게 고민하고 실제 서비스에 적용하며 **사용자 경험 최적화 역량**을 키웠습니다.',
        '또한 Datadog, Hotjar, Google Analytics와 같은 **데이터 분석 및 모니터링 도구를 적극 활용**하여 주요 지표를 분석하고, 이를 근거로 한 **데이터 기반의 의사결정 경험**을 쌓을 수 있었습니다.',
      ],
      employmentStatus: 'retire',
      historyList: [
        {
          department: '개발팀',
          role: '프론트엔드 개발자',
          period: ['2021-12-29', '2023-02-21'],
          workingList: [
            'B2B SaaS 솔루션 “웰로비즈” 개발 런칭',
            'B2C 정책 큐레이션 서비스 “웰로” 리뉴얼',
            '웰로 회원가입 프로세스 데이터 기반 개선 (A/B 테스트)',
            '웰로 디자인 시스템 구축/개발',
            '정부 정책 노출 Sitemap SEO 중복 이슈 개선 및 고도화',
            '타사솔루션 내부 컴포넌트 라이브러리로 리팩토링',
            '사업일정관리 캘린더 기능 개발',
            '엑셀 업로드, 다운로드, 비밀번호 기능 공통 유틸 함수 개발',
          ],
          skillNameList: [
            'vue.js',
            'nuxt.js',
            'sass',
            'element-ui',
            'vuex',
            'datadog',
            'gtm',
            'ga',
            'hackle',
            'hotjar',
            'jira',
            'confluence',
          ],
        },
      ],
    },
    {
      companyName: '위펀',
      logoName: 'wefun',
      serviceSummary: [
        '직원 복지를 위한 **B2B 구독 통합 서비스 개발 운영** (간식 구독 서비스 “스낵24”, 임직원 선물 발송 솔루션 “선물24”, 임직원 식대 관리 솔루션 “식권24” 등)',
      ],
      experienceSummary: [
        '백엔드, 프론트 소스코드가 하나의 레포지토리에서 관리되는 환경을 멀티레포로 전환하는 과정에서 **프로젝트 관리 및 프로젝트 구조 설계**에 대한 이해를 높일 수 있었습니다.',
        '동료들과 함께 코드 컨벤션을 정립하고 서비스 페이지 최적화를 위한 리팩토링을 주도적으로 수행하며 실질적인 **서비스 개선 경험**을 쌓았습니다.',
      ],
      employmentStatus: 'retire',
      historyList: [
        {
          department: '개발팀',
          role: '프론트엔드 개발자',
          period: ['2021-06-01', '2021-12-25'],
          workingList: [
            '스낵24, 선물24 해피콜 서비스 관리자 페이지 마이그레이션',
            '타사 웹 호스팅 서비스를 통해 관리하던 서비스 소개 랜딩 페이지를 적응형 자사 서비스로 내제화',
            'Form 유효성 검증 컴포넌트 개발',
            '하이브리드앱 웹앱 서비스 식권24 개발 설계 참여 (브릿지 함수 정의, 설계)',
            '카카오맵 커스텀 오버레이 마커 선택 고도화 기능 개발',
            '식권24 서비스 프로젝트 설계 및 개발',
          ],
          skillNameList: [
            'vue.js',
            'nuxt.js',
            'sass',
            'element-ui',
            'vuex',
            'gtm',
            'ga',
            'hotjar',
            'jQuery',
            'jira',
            'confluence',
          ],
        },
      ],
    },
    {
      companyName: '하이브랩',
      logoName: 'hivelab',
      serviceSummary: ['삼성전자 글로벌 웹페이지 **CMS 솔루션 위젯** 개발', '**사내 ERP** 개발'],
      experienceSummary: [
        '삼성전자 글로벌 웹페이지 CMS 개발자로 삼성 프로젝트에 참여하며 자연스럽게 프론트엔드 개발에 흥미를 가지게 되었고, 동료 프론트엔드 개발자분과 스터디를 진행하고 서비스에 적용하며 프론트엔드 개발 역량을 키웠습니다.',
        '사내 시스템 개발 및 운영을 담당하며 Java 기반의 백엔드 개발, 데이터베이스 쿼리 튜닝, Linux 서버 환경 인프라 관리 경험 등을 통해 실무 경험의 폭을 넓힐 수 있었습니다.',
      ],
      employmentStatus: 'retire',
      historyList: [
        {
          department: 'BE개발팀',
          role: '백엔드 전임 개발자',
          period: ['2018-04-09', '2020-12-11'],
          workingList: [
            '삼성 글로벌 사이트 CMS 솔루션 위젯, 페이지 개발',
            '사내 시스템 개발 및 운영',
            '사내 인프라 관리 (로컬 Gitlab, 로컬 리눅스 서버, 사내 Wiki 서버 등)',
          ],
          skillNameList: [
            'vue.js',
            'vuex',
            'sass',
            'jQuery',
            'java',
            'spring boot',
            'ubuntu linux',
            'jira',
            'confluence',
          ],
        },
      ],
    },
  ],
  isUsedTotalPeriod: true,
}

export default experience
