import { IExperience } from '@/app/(pages)/resume/_components/experience/types'

const experience: IExperience = {
  experienceList: [
    {
      companyName: '라우드',
      logoName: 'laud',
      summary: [
        '인테리어 “견적-상담-직시공” 과정을 간소화하여 사용자와 인테리어 업자를 연결하는 **인테리어 B2C 서비스 “디어마이홈” 개발 운영**',
        '**서비스 개발의 0 to 1을 경험**하고, 프론트엔드 팀장 역할을 같이하여 **팀원 관리 능력**을 성장시키기 위해 노력했습니다.',
      ],
      employmentStatus: 'recommended_retire',
      historyList: [
        {
          department: '프로덕트팀',
          role: '프론트엔드 팀장',
          period: ['2024-04-15', '2025-04-15'],
          workingList: [
            'B2C 인테리어 직시공 & B2B 인테리어 자재몰 서비스 “디어마이홈” 개발',
            '챗봇 대화형 견적 상담 기능 설계/개발',
            '카카오맵을 이용한 시공사례 인테리어 지도 기능 개발',
            '디어마이홈 Flutter 하이브리드 앱 개발/배포/운영',
            '어드민 개발 (디어마이홈, FCM 메세지서버)',
            '프론트엔드 모노레포 설계/세팅',
            '프론트엔드 AWS 배포 파이프라인, CI/CD 관리',
          ],
          skillNameList: [
            'react.js',
            'next.js 14 app router',
            'typescript',
            'zustand',
            'react-query',
            'react-hook-form',
            'tailwind-css',
            'turborepo',
            'flutter',
            'github-actions',
            'aws',
            'gtm',
            'ga',
            'jira',
            'confluence',
          ],
        },
      ],
    },
    {
      companyName: '비엘큐',
      logoName: 'blq',
      summary: [
        '전자제품 판매, 체험, 중고판매 등 사용자 경험이 구매로 이어질 수 있는 **B2C 전자제품 커머스 “테스트밸리” 개발 운영**',
        '사진 감가 분석 AI로 감가 금액을 측정하여 중고 전자제품을 매입하고, 사용자간의 중고 거래를 중계하는 **B2B2C 중고거래 서비스 “퀵셀” 개발 운영**',
      ],
      employmentStatus: 'recommended_retire',
      historyList: [
        {
          department: '프로덕트팀',
          role: '프론트엔드 개발자',
          period: ['2023-05-22', '2024-02-29'],
          workingList: [
            'B2C 전자제품 체험,구매 서비스 “테스트벨리” 개발',
            'B2C 중고거래, 중고 제품 자사 매입/판매 서비스 “퀵셀” 어드민 개발',
            'FCM 메세지서버 어드민 개발',
            '테스트밸리 프로모션 이벤트 페이지 빌더 설계/개발',
            '어드민 모노레포 마이그레이션 설계/개발',
            '상세페이지 페이지 성능 분석/최적화',
            '검색/기획전/상세페이지 SEO 개선을 위한 Sitemap 등록 기능 개발',
          ],
          skillNameList: [
            'react.js',
            'next.js 13 app router',
            'typescript',
            'zustand',
            'redux',
            'react-query',
            'react-hook-form',
            'tailwind-css',
            'emotion',
            'daisyUI',
            'ant-design',
            'turborepo',
            'github-actions',
            'aws ec2',
            'gtm',
            'ga',
            'hackle',
            'jira',
            'confluence',
          ],
        },
      ],
    },
    {
      companyName: '웰로',
      logoName: 'wello',
      summary: [
        '국민의 정책 소외 문제를 해결하기 위한 **B2C 정책 큐레이션 서비스 “웰로” 개발 운영**',
        '정부의 기업 지원정책 추천, 매칭, 관리 구독형 **B2B SaaS 솔루션 “웰로비즈” 개발 운영**',
      ],
      employmentStatus: 'retire',
      historyList: [
        {
          department: '프로덕트팀',
          role: '프론트엔드 개발자',
          period: ['2021-12-29', '2023-02-21'],
          workingList: [
            'B2B SaaS 솔루션 “웰로비즈” 개발 런칭',
            'B2C 정책 큐레이션 서비스 “웰로” 리뉴얼',
            '웰로 회원가입 프로세스 데이터 기반 개선 (A/B 테스트)',
            '웰로 디자인 시스템 구축/개발',
            '정부 정책 노출 Sitemap SEO 중복 이슈 개선 및 고도화',
            '타사솔루션 내부 컴포넌트 라이브러리로 리팩토링',
            '사업일정관리 캘린더 기능 개발',
            '엑셀 업로드, 다운로드, 비밀번호 기능 공통 유틸 함수 개발',
          ],
          skillNameList: [
            'vue.js',
            'nuxt.js',
            'sass',
            'element-ui',
            'vuex',
            'datadog',
            'gtm',
            'ga',
            'hackle',
            'hotjar',
            'jira',
            'confluence',
          ],
        },
      ],
    },
    {
      companyName: '위펀',
      logoName: 'wefun',
      summary: [
        '직원 복지를 위한 **B2B 구독 통합 서비스 개발 운영** (간식 구독 서비스 “스낵24”, 임직원 선물 발송 솔루션 “선물24”, 임직원 식대 관리 솔루션 “식권24” 등)',
      ],
      employmentStatus: 'retire',
      historyList: [
        {
          department: '개발팀',
          role: '프론트엔드 개발자',
          period: ['2021-06-01', '2021-12-25'],
          workingList: [
            '해피콜 서비스 관리자 페이지 마이그레이션',
            '타사 웹 호스팅 서비스를 통해 관리하던 서비스 소개 랜딩 페이지를 적응형 자사 서비스로 내제화',
            'Form validation 컴포넌트 개발',
            '하이브리드앱 웹앱 서비스 식권24 개발 설계 참여 (브릿지 함수 정의, 설계)',
            '카카오맵 커스텀 오버레이 마커 선택 고도화 기능 개발',
          ],
          skillNameList: [
            'vue.js',
            'nuxt.js',
            'sass',
            'element-ui',
            'vuex',
            'gtm',
            'ga',
            'hotjar',
            'jQuery',
            'jira',
            'confluence',
          ],
        },
      ],
    },
    {
      companyName: '하이브랩',
      logoName: 'hivelab',
      summary: [''],
      employmentStatus: 'retire',
      historyList: [
        {
          department: 'BE개발팀',
          role: '백엔드 전임 개발자',
          period: ['2018-04-09', '2020-12-11'],
          workingList: [],
          skillNameList: [
            'vue.js',
            'vuex',
            'sass',
            'jQuery',
            'java',
            'spring boot',
            'ubuntu linux',
            'jira',
            'confluence',
          ],
        },
      ],
    },
  ],
  isUsedTotalPeriod: true,
}

export default experience
